input:
  root: RootObject
  objects:
    RootObject:
      id: RootObject
      properties:
        kubeconfig:
          display:
            description: The complete kubeconfig file as a string
            name: Kubeconfig file contents
          type:
            type_id: string
        run_id:
          display:
            description: A unique run identifier for tracking groups of workflows triggered by external automation/CI
            name: Run ID
          type:
            type_id: string
          default: "\"\""
          required: false
steps:
  uuidgen:
    plugin: quay.io/arcalot/arcaflow-plugin-utilities:latest
    step: uuid
    input: {}
  kubeconfig:
    plugin: quay.io/arcalot/arcaflow-plugin-kubeconfig:latest
    input:
      kubeconfig: !expr $.input.kubeconfig
  uperf_server:
    plugin: quay.io/arcalot/arcaflow-plugin-uperf:latest
    step: uperf_server
    deploy:
      type: kubernetes
      connection: !expr $.steps.kubeconfig.outputs.success.connection
      pod:
        metadata:
          namespace: default
          labels:
            arcaflow: uperf
        spec:
          pluginContainer:
            imagePullPolicy: Always
    input:
      run_duration: 60
      port: 20000
  service:
    plugin: quay.io/arcalot/arcaflow-plugin-service:latest
    input:
      connection: !expr $.steps.kubeconfig.outputs.success.connection
      service:
        metadata:
          namespace: default
        spec:
          ports:
           - name: control
             port: 20000
             protocol: TCP
           - name: controludp
             port: 20000
             protocol: UDP
           - name: workload
             port: 30000
             protocol: TCP
           - name: workloadudp
             port: 30000
             protocol: UDP
          selector:
            arcaflow: uperf
  uperf_client:
    plugin: quay.io/arcalot/arcaflow-plugin-uperf:latest
    step: uperf
    deploy:
      type: kubernetes
      connection: !expr $.steps.kubeconfig.outputs.success.connection
      pod:
        spec:
          pluginContainer:
            imagePullPolicy: Always
    input:
      port: 20000
      name: "netperf"
      groups:
        - nthreads: 1
          transactions:
            - iterations: 1
              flowops:
                - type: "accept"
                  remotehost: !expr $.steps.service.outputs.success.name
                  port: 20000
                  protocol: "tcp"
            - duration: "10s"
              flowops:
                - type: "write"
                  size: 64
                - type: "read"
                  size: 64
            - iterations: 1
              flowops:
                - type: "disconnect"
  metadata:
    plugin: quay.io/arcalot/arcaflow-plugin-metadata:latest
    deploy:
      type: kubernetes
      connection: !expr $.steps.kubeconfig.outputs.success.connection
      pod:
        spec:
          pluginContainer:
            imagePullPolicy: Always
    input: {}
output:
  uuid: !expr $.steps.uuidgen.outputs.success.uuid
  run_id: !expr $.input.run_id
  uperf: !expr $.steps.uperf_client.outputs.success
  metadata: !expr $.steps.metadata.outputs.success
