name: Build
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
jobs:
  lint_and_test:
    name: lint and test
    uses: arcalot/arcaflow-reusable-workflows/.github/workflows/go_lint_and_test.yaml@main
    with:
      go_version: ${{ vars.ARCALOT_GO_VERSION }}
  generate:
    name: go generate
    uses: arcalot/arcaflow-reusable-workflows/.github/workflows/go_generate.yaml@main
    with:
      go_version: ${{ vars.ARCALOT_GO_VERSION }}
  release:
    name: release
    permissions:
      contents: write
      packages: write
    needs:
      - lint_and_test
      - generate
    uses: arcalot/arcaflow-reusable-workflows/.github/workflows/go_release.yaml@update-go-lint-and-test  # FIXME:  SHOULD BE @main
    secrets:
      REGISTRY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
    with:
      go_version: ${{ vars.ARCALOT_GO_VERSION }}
      for_release: ${{ startsWith(github.event.ref, 'refs/tags/') }}
      registry: quay.io
  build_python_wheel:
    name: build python wheel
    needs:
      - release
    uses: arcalot/arcaflow-reusable-workflows/.github/workflows/python_release.yaml@main
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
    with:
      python_version: ${{ vars.ARCALOT_PYTHON_VERSION }}
